### ISSUE TITLE
Notify if there is no connection with the server/database

### ISSUE THREAD

**Issue by Thijs----** [Michvw/Responsive-html-domotica-interface#8]
If the site is loaded, but there's no connection with the server, you'll not know. The switches will work, but this won't result in real changes (or changes in the database). Also if a switch/sensor changes, you wont know.

So if connection fails: notify the user!

**Comment by Michvw** [comment]
Done, if connection fails you get redirected to an error page. if you're on the error page and manage to connect to the server you'll get automatically redirected to the home page
